FROM node:20.18.0-alpine

WORKDIR /youapp_fullstack_project/you-app-backend/auth-microservice

COPY ./api-gateway/package*.json ./

RUN npm ci

COPY ./api-gateway .

EXPOSE 4001

CMD ["npm", "run", "start:dev"]
