FROM node:20.18.0-alpine

# Set working directory to the shared folder
WORKDIR /youapp_fullstack_project/you-app-backend/shared

# Copy only package files first to install dependencies
COPY package*.json ./

RUN npm install


# Copy the rest of the shared folder files
COPY . .
